### PR TITLE
Refactor symphony data access to use a single patron query to rule them all

### LINKED ISSUE #169: Refactor Symphony data access patterns
- reduce duplicate requests (or consolidate requests that could be combined into a single request)

### PR DESCRIPTION
**Pull request by cbeer**
Off-hand, it seems 30-50% slower than requests for just a single data type, but also significantly faster than making multiple Symphony API calls.

This should unblock some the work on #131, #120 (which need both checkouts + fines data) and #52 (which needs all the things...).

Fixes #169

### CODE REVIEW

**Comment by mejackreed** [comment]
Do we have a use case where we still may want an individual request for some client side / json interaction response thing? Perhaps not now at this moment, but thinking about maybe we need to return only checkout / fine information for something individually?

**Comment by cbeer** [comment]
When you say individually, do you mean just the patron's list of e.g. checkouts, or information about a specific checkout? If the former, I think we're already seeing that the three tabs need data from multiple lists (e.g. checkouts + fines) in order to create the desired behavior. If the latter, maybe; although I suppose we'd retrieve the resource directly instead of diving through the patron resource.

**Comment by mejackreed** [comment]
Yeah I think I was referring the first, but the second also seems plausible. I'm 👍 with this approach here.

**Comment by cbeer** [comment]
Yeah, for the first, I think we have some options.. maybe a method signature like:

`def patron_info(patron_key, include: [:checkouts, :fines, :requests])`

🤷‍♂

**Pull request merged**
